GET http://localhost:8000

### Register

POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
      "did": "did:kilt:4sBCQNWZAL9UkzEzSq56NFPecEzRysjsdAqigY1cPQbuK1W1"
}    

### Login

POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
      "did": "did:kilt:4qNLDkBxZDaM5U2jKkHro4xkQsyhnXFWMvQJ71WzAfDM51WU"
}

### Create Chat
POST http://localhost:8000/api/v1/chat/createChat
Content-Type: application/json

{
      "senderId":"6458b485264f3eb05e7f333f",
      "receiverId":"6459e96b08d4a18fa3802f00"
}

### Find One User Chat 

GET http://localhost:8000/api/v1/chat/6458b485264f3eb05e7f333f

### Find Both User Chat

GET http://localhost:8000/api/v1/chat/find/6458b485264f3eb05e7f333f/6458bf1528c2ebf30ee34dcd

### Add Message

POST http://localhost:8000/api/v1/message/addMessage
Content-Type: application/json

{
      "chatId":"6458c00a47d39b2e6c2825d0",
      "senderId":"6458b485264f3eb05e7f333f",
      "text":"Hello Again"
}

### Find All Message

GET http://localhost:8000/api/v1/message/6458c00a47d39b2e6c2825d0

### GET USER

GET http://localhost:8000/api/v1/user/6458b485264f3eb05e7f333f

### GET ALL USER

GET http://localhost:8000/api/v1/user

